name: Deploy Web and Admin to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Web & Admin
        run: pnpm turbo run build --filter=web --filter=admin --force

      - name: Prepare Deployment Folder
        run: |
          mkdir -p final-deploy
          cp -r apps/web/dist/* final-deploy/

          mkdir -p final-deploy/admin
          cp -r apps/admin/dist/* final-deploy/admin

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: final-deploy
          branch: gh-pages
          clean: true